name: learn-github-actions

on: 
  push:
    branches:
        - main
        - new_devops_branch
    #     - 'main/**'   //doubt
  #   # paths:
  #   #   - '**.txt'
  # pull_request:
  #   branches:   
  #     - new_devops_branch
  #     - 'main/**'

  # schedule:
  #     - cron: '20 17 * * *'

env:
  SCRIPT_NAME: my_script.py

jobs:
  check-Python-version-and-run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: print Python version 
        run: python --version

      - name: Run python script
        run: |
          cd Demo
          python $SCRIPT_NAME



# name: learn-cron-actions

# on:
#   schedule:
#     - cron: '17 20 * * '

# jobs:
#   test_schedule:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Not on Monday or Wednesday
#         if: github.event.schedule != '30 5 * * 1,3'
#         run: echo "This step will be skipped on Monday and Wednesday"
#       - name: Every time
#         run: echo "This step will always run"         